server:
  port: 6003

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,zipkin"
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    brave:
      span-handler:
        enabled: true
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: saga-orchestrator
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/saga_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      definition: orderProcessor;stockResponseProcessor;paymentResponseProcessor
    stream:
      bindings:
        #ORDER
        orderProcessor-in-0:
          destination: order-events
          group: saga-order-group
          consumer:
            maxAttempts: 4
            backOffInitialInterval: 1000
            backOffMaxInterval: 10000
            backOffMultiplier: 2.0

        #STOCK
        stockResponseProcessor-in-0:
          destination: stock-events
          group: saga-stock-group
          consumer:
            maxAttempts: 4
            backOffInitialInterval: 1000
            backOffMaxInterval: 10000
            backOffMultiplier: 2.0

        #PAYMENT
        paymentResponseProcessor-in-0:
          destination: payment-events
          group: saga-payment-group
          consumer:
            maxAttempts: 4
            backOffInitialInterval: 1000
            backOffMaxInterval: 10000
            backOffMultiplier: 2.0

        orderResponse-out-0:
          destination: order-status-updates
        stock-out-0:
          destination: stock-commands
        payment-out-0:
          destination: payment-commands
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          orderProcessor-in-0:
            consumer:
              enableDlq: true
              dlqName: order-events.dlq
          stockResponseProcessor-in-0:
            consumer:
              startOffset: earliest
              enableDlq: true
              dlqName: stock-events.dlq
          paymentResponseProcessor-in-0:
            consumer:
              enableDlq: true
              dlqName: payment-events.dlq

app:
  redis-lock:
    key-prefix: saga-orchestrator
    wait-timeout: 2s
    lease-time: 10s
    retry-interval: 50ms