server:
  port: 6004

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,zipkin"
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    brave:
      span-handler:
        enabled: true
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: stock-service
  cloud:
    function:
      definition: stockProcessor
    stream:
      bindings:
        stockProcessor-in-0:
          content-type: application/json
          destination: stock-commands
          group: stock-service-group
          consumer:
            maxAttempts: 4
            backOffInitialInterval: 1000
            backOffMaxInterval: 10000
            backOffMultiplier: 2.0
        stockResponse-out-0:
          destination: stock-events
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          stockProcessor-in-0:
            consumer:
              enableDlq: true
              dlqName: stock-commands.dlq

  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update

