server:
  port: 6001

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,zipkin"
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    brave:
      span-handler:
        enabled: true
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: order-service
  cloud:
    function:
      definition: orderFinalizer # buraya orderSource yazmadık çünkü orderSource sadece event yayınlayacak, herhangi bir event dinlemeyecek
    stream:
      bindings:
        orderSource-out-0:
          destination: order-events
        orderFinalizer-in-0:
          destination: order-status-updates
          group: order-service-group
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          orderFinalizer-in-0:
            consumer:
              startOffset: earliest

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update